app/courses/models.py
from flask import current_app, request
from flask.ext.login import UserMixin, AnonymousUserMixin
from app.core import db


course_users = db.Table('course_users',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id'), primary_key=True),
    db.Column('course_id', db.Integer, db.ForeignKey('courses.id'), primary_key=True)
)


class Course(db.Model):
    __tablename__ = 'courses'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    instructor_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    instructor = db.relationship('User', foreign_keys=[instructor_id], backref=db.backref('created_courses', order_by=id))
    students = db.relationship('User', secondary=course_users, backref=db.backref('courses', lazy='dynamic'))
    assignments = db.relationship('Assignment', backref='course', lazy='dynamic')

    def __repr__(self):
        return '<Course %r>' % self.name


class Assignment(db.Model):
    __tablename__ = 'assignments'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    course_id = db.Column(db.Integer, db.ForeignKey('courses.id'))
    submissions = db.relationship('Submission', backref='assignment', lazy='dynamic')

    def __repr__(self):
        return '<Assignment %r>' % self.name


class Submission(db.Model):
    __tablename__ = 'submissions'
    id = db.Column(db.Integer, primary_key=True)
    file_name = db.Column(db.Text)
    student_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    student = db.relationship('User', foreign_keys=[student_id], backref=db.backref('submissions', order_by=id))
    assignment_id = db.Column(db.Integer, db.ForeignKey('assignments.id'))

    def __repr__(self):
        return '<Submission %r>' % self.file_name

app/courses/forms.py
from flask.ext.wtf import Form
from flask_wtf.file import FileField
from wtforms import StringField, PasswordField, BooleanField, SubmitField,\
    TextAreaField, SelectField
from wtforms.validators import Required, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from .models import Course


class CreateCourseForm(Form):
    name = StringField('Name', validators=[Required()])
    submit = SubmitField('Create Course')


class AssignmentForm(Form):
    name = StringField('Name', validators=[Required()])
    submit = SubmitField('Add Assignment')


class SubmissionForm(Form):
    file = FileField('Submission')
    submit = SubmitField('Submit')


class CourseForm(Form):
    course_id = StringField('Course ID', validators=[Required()])
    submit = SubmitField('Add Course')

    def validate_course_id(self, field):
        try:
            num = int(field.data)
        except:
            raise ValidationError('Course Id is not valid.')

class DeleteCourseForm(Form):
    submit = SubmitField('End Course')

app/courses/__init__.py
from flask import Blueprint

courses = Blueprint('courses', __name__)

from . import views

app/courses/views.py
import os
import shutil
from werkzeug import secure_filename
from flask import abort, render_template, redirect, request, url_for, flash, current_app, send_from_directory
from flask.ext.login import current_user, login_required
from app.core import db
from . import courses
from .models import Course, Assignment, Submission
from .forms import CourseForm, CreateCourseForm, AssignmentForm, SubmissionForm, DeleteCourseForm


@courses.route('/courses/create', methods=['GET', 'POST'])
@login_required
def create_course():
    if current_user.role.name != 'Instructor':
        abort(404)

    form = CreateCourseForm()
    if form.validate_on_submit():
        course = Course(name=form.name.data,
                        instructor=current_user)

        db.session.add(course)
        db.session.commit()
        return redirect(url_for('courses.view_course', id=course.id))
    return render_template('courses/create.html', form=form)


@courses.route('/courses/add', methods=['GET', 'POST'])
@login_required
def add_course():
    form = CourseForm()
    if form.validate_on_submit():
        course = Course.query.get(form.course_id.data)
        current_user.courses.append(course)
        db.session.commit()
        return redirect(url_for('accounts.user', username=current_user.username))
    return render_template('courses/add.html', form=form)

@courses.route('/courses/<id>', methods=['GET', 'POST'])
@login_required
def view_course(id):
    course = Course.query.get_or_404(id)
    if course not in current_user.courses and course not in current_user.created_courses:
        abort(404)
    form = AssignmentForm()
    if form.validate_on_submit():
        assignment = Assignment(name=form.name.data,
                                course=course)
        db.session.add(assignment)
        db.session.commit()
        # create folder in submissions
        if not os.path.exists(os.path.join(current_app.config['SUBMISSION_FOLDER'], str(assignment.id))):
            os.makedirs(os.path.join(current_app.config['SUBMISSION_FOLDER'], str(assignment.id)))

        return redirect(url_for('courses.view_course', id=course.id))
    return render_template('courses/view.html', course=course, form=form)


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


@courses.route('/courses/<course_id>/<assignment_id>', methods=['GET', 'POST'])
@login_required
def view_assignment(course_id, assignment_id):
    course = Course.query.get_or_404(course_id)
    if course not in current_user.courses and course not in current_user.created_courses:
        abort(404)
    assignment = Assignment.query.get_or_404(assignment_id)
    if assignment not in course.assignments:
        abort(404)
    form = SubmissionForm()
    if form.validate_on_submit():
        filename = secure_filename(form.file.data.filename)
        if not os.path.exists(os.path.join(current_app.config['SUBMISSION_FOLDER'], str(assignment.id), current_user.username)):
            os.makedirs(os.path.join(current_app.config['SUBMISSION_FOLDER'], str(assignment.id), current_user.username))

        form.file.data.save(os.path.join(current_app.config['SUBMISSION_FOLDER'], str(assignment.id), current_user.username, filename))
        submission = Submission(file_name=filename, assignment=assignment, student=current_user)
        db.session.add(submission)
        db.session.commit()
        flash('Submission Uploaded')
        return redirect(url_for('courses.view_assignment', course_id=course.id, assignment_id=assignment.id))
    submissions = Submission.query.filter_by(assignment_id=assignment_id, student_id=current_user.id)
    return render_template('courses/view_assignment.html', course=course, assignment=assignment, form=form, submissions=submissions)


@courses.route('/courses/<course_id>/<assignment_id>/<submission_id>')
@login_required
def view_submission(course_id, assignment_id, submission_id):
    course = Course.query.get_or_404(course_id)
    if course not in current_user.courses and course not in current_user.created_courses:
        abort(404)
    assignment = Assignment.query.get_or_404(assignment_id)
    if assignment not in course.assignments:
        abort(404)
    submission = Submission.query.get_or_404(submission_id)
    if submission not in assignment.submissions:
        abort(404)
    return render_template('courses/view_submission.html', course=course, assignment=assignment, submission=submission)


@courses.route('/courses/<course_id>/<assignment_id>/download')
@login_required
def download_all_submissions(course_id, assignment_id):
    course = Course.query.get_or_404(course_id)
    if course not in current_user.courses and course not in current_user.created_courses:
        abort(404)
    assignment = Assignment.query.get_or_404(assignment_id)
    if assignment not in course.assignments:
        abort(404)
    shutil.make_archive(
        os.path.join(current_app.config['SUBMISSION_FOLDER'], str(assignment.id) + assignment.name),
        'zip',
        os.path.join(current_app.config['SUBMISSION_FOLDER'], str(assignment.id)))
    return send_from_directory(current_app.config['SUBMISSION_FOLDER'], str(assignment.id) + assignment.name + '.zip',
                               as_attachment=True, attachment_filename=str(assignment.id) + assignment.name)

@courses.route('/courses/<course_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_course(course_id):
    course = Course.query.get_or_404(course_id)
    if course not in current_user.created_courses:
        abort(404)
    form = DeleteCourseForm()
    if form.validate_on_submit():
        course = Course.query.get(course_id)
        db.session.delete(course)
        db.session.commit()
        return redirect(url_for('accounts.user', username=current_user.username))
    return render_template('courses/delete.html', form=form)

app/templates/courses/add.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Hansel - Add Course{% endblock %}

{% block page_content %}
<div class="page-header">
    Add Course
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/courses/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Hansel - {{ user.username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    Create Course
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/courses/delete.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Hansel - End Course{% endblock %}

{% block page_content %}
<div class="page-header">
    End Course?
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/courses/view.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Hansel - {{ course.name }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ course.name }}</h1>

    <ul>
    {% for assignment in course.assignments %}
      <li><a href="{{ url_for('courses.view_assignment', course_id=course.id, assignment_id=assignment.id) }}">{{ assignment.name }}</a></li>
    {% endfor %}
    </ul>
    {% if current_user.role.name == 'Instructor' %}
    <h3>Create Assignment</h3>
    {{ wtf.quick_form(form) }}
    <br>
    <a href="{{ url_for('courses.delete_course', course_id=course.id) }}" class="btn btn-danger">End Course</a>
    {% endif %}
</div>
{% endblock %}

app/templates/courses/view_assignment.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Hansel - {{ assignment.name }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ assignment.name }}</h1>

    {% if current_user.role.name == 'Instructor' %}
      <ul>
      {% for submission in assignment.submissions %}
        <li><a href="{{ url_for('courses.view_submission', course_id=course.id, assignment_id=assignment.id, submission_id=submission.id) }}">{{ submission.student.username }} | {{ submission.file_name }}</a></li>
      {% endfor %}
      </ul>
      <a href="{{ url_for('courses.download_all_submissions', course_id=course.id, assignment_id=assignment.id) }}">Download All Submissions</a>
    {% else %}
      {% if submissions %}
        <h2>Already Submitted</h2>
        {% for submission in submissions %}
          {% if submission.student_id == current_user.id %}
            <p>{{ submission.file_name }}</p>
          {% endif %}
        {% endfor %}
      {% endif %}
      <br>
      <form method="post" class="form" role="form" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ form.file }}

        <input class="btn btn-default" id="submit" name="submit" type="submit" value="Submit">
      </form>
    {% endif %}
</div>
{% endblock %}

app/templates/courses/view_submission.html
{% extends "base.html" %}

{% block title %}Hansel - {{ submission.name }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ submission.file_name }}</h1>
    <p>User: {{ submission.student.username }}</p>
</div>
{% endblock %}